Repository jupyter/jupyter_client, pull requests merged in 2021-07, with the labels that each got.

#612 Kernel Provisioning - initial implementation
  .github/workflows/main.yml
  docs/api/index.rst
  docs/api/manager.rst
  docs/api/provisioners.rst
  docs/index.rst
  docs/provisioning.rst
  jupyter_client/__init__.py
  jupyter_client/connect.py
  jupyter_client/kernelspec.py
  jupyter_client/kernelspecapp.py
  jupyter_client/launcher.py
  jupyter_client/manager.py
  jupyter_client/multikernelmanager.py
  jupyter_client/provisioning/__init__.py
  jupyter_client/provisioning/factory.py
  jupyter_client/provisioning/local_provisioner.py
  jupyter_client/provisioning/provisioner_base.py
  jupyter_client/tests/conftest.py
  jupyter_client/tests/test_kernelmanager.py
  jupyter_client/tests/test_provisioning.py
  jupyter_client/tests/utils.py
  requirements.txt
  setup.py
Labels: enhancement

#648 Add status field to other replies in documentation
  docs/messaging.rst
Labels: documentation

#652 Change to edit_magic payload
  docs/messaging.rst
Labels: documentation

#644 Test downstream projects
  .github/workflows/downstream.yml
Labels: maintenance

#486 Added debugger key in kernel_info_reply
  docs/messaging.rst
Labels: enhancement
