Repository jupyter/jupyter_client, pull requests merged in 2021-11, with the labels that each got.

#720 Enforce labels on PRs
  .github/workflows/enforce-label.yml
Labels: maintenance

#717 Improve restarter logic
  jupyter_client/ioloop/restarter.py
  jupyter_client/provisioning/provisioner_base.py
  jupyter_client/restarter.py
  jupyter_client/tests/problemkernel.py
  jupyter_client/tests/test_restarter.py
Labels: bug

#712 Add support for pending kernels
  jupyter_client/manager.py
  jupyter_client/multikernelmanager.py
  jupyter_client/tests/test_kernelmanager.py
  jupyter_client/tests/test_kernelspec.py
  jupyter_client/tests/test_multikernelmanager.py
  jupyter_client/tests/utils.py
Labels: enhancement

#721 Automated Changelog Entry for 7.1.0 on master
  CHANGELOG.md
Labels: documentation
