Repository jupyter/jupyter_client, pull requests merged in 2021-08, with the labels that each got.

#670 Fix up some async method aliases in KernelManager
  jupyter_client/manager.py
Labels: bug

#672 Rename trait to allowed_kernelspecs
  jupyter_client/kernelspec.py
  jupyter_client/tests/test_kernelspec.py
Labels: maintenance

#673 Update changelog for 7.0.0rc0
  docs/changelog.rst
Labels: documentation

#674 Fix project name
  jupyter_client/kernelspec.py
Labels: maintenance

#676 Prepare for use with Jupyter Releaser
  .github/workflows/check-release.yml
  .github/workflows/main.yml
  .gitignore
  CHANGELOG.md
  MANIFEST.in
  README.md
  RELEASING.md
  docs/api/client.rst
  docs/changelog.rst
  docs/conf.py
  docs/messaging.rst
  jupyter_client/_version.py
  jupyter_client/session.py
  jupyter_client/ssh/tunnel.py
  pyproject.toml
  requirements-doc.txt
  setup.cfg
  setup.py
Labels: maintenance

#675 Force install jupyter_client master
  .github/workflows/downstream.yml
Labels: maintenance

#681 Create migration.md
  docs/index.rst
  docs/migration.md
Labels: documentation

#680 Update changelog for 7.0 Release
  CHANGELOG.md
Labels: documentation

#679 Automated Changelog Entry for 7.0.0 on master
  CHANGELOG.md
Labels: documentation

#685 Improve migration guide
  docs/migration.md
Labels: documentation

#686 Don't set event loop policy on Windows at import time
  jupyter_client/utils.py
Labels: bug

#687 Automated Changelog Entry for 7.0.2 on master
  CHANGELOG.md
Labels: documentation

#688 use load_connection_info(info) when constructing a blocking client
  jupyter_client/connect.py
Labels: bug
