Repository jupyter/jupyter_client, pull requests merged in 2022-04, with the labels that each got.

#764 More Cleanup
  .github/workflows/downstream.yml
  .github/workflows/main.yml
  .mailmap
  .pre-commit-config.yaml
  docs/kernels.rst
  docs/messaging.rst
  docs/pending-kernels.rst
  docs/provisioning.rst
  docs/wrapperkernels.rst
  jupyter_client/connect.py
  jupyter_client/kernelspec.py
  jupyter_client/launcher.py
  jupyter_client/localinterfaces.py
  jupyter_client/manager.py
  jupyter_client/provisioning/provisioner_base.py
  jupyter_client/session.py
  jupyter_client/ssh/tunnel.py
  jupyter_client/tests/test_adapter.py
  jupyter_client/tests/test_connect.py
  jupyter_client/tests/test_kernelmanager.py
  jupyter_client/tests/test_restarter.py
  jupyter_client/threaded.py
  pyproject.toml
  setup.cfg
Labels: maintenance

#766 Include py.typed file
  MANIFEST.in
  jupyter_client/py.typed
  setup.py
Labels: maintenance

#767 Automated Changelog Entry for 7.2.2 on main
  CHANGELOG.md
Labels: documentation

#768 Clean up pre-commit
  .github/workflows/main.yml
  .pre-commit-config.yaml
  README.md
Labels: maintenance

#769 Improve mypy config
  .github/workflows/main.yml
  .pre-commit-config.yaml
  docs/conf.py
  jupyter_client/adapter.py
  jupyter_client/asynchronous/client.py
  jupyter_client/blocking/client.py
  jupyter_client/channels.py
  jupyter_client/client.py
  jupyter_client/connect.py
  jupyter_client/consoleapp.py
  jupyter_client/kernelapp.py
  jupyter_client/kernelspec.py
  jupyter_client/kernelspecapp.py
  jupyter_client/launcher.py
  jupyter_client/localinterfaces.py
  jupyter_client/manager.py
  jupyter_client/multikernelmanager.py
  jupyter_client/provisioning/factory.py
  jupyter_client/provisioning/local_provisioner.py
  jupyter_client/provisioning/provisioner_base.py
  jupyter_client/restarter.py
  jupyter_client/runapp.py
  jupyter_client/session.py
  jupyter_client/ssh/forward.py
  jupyter_client/ssh/tunnel.py
  jupyter_client/threaded.py
  jupyter_client/win_interrupt.py
  pyproject.toml
  setup.py
Labels: maintenance

#772 Fix shutdown and cleanup behavior
  .github/workflows/main.yml
  jupyter_client/channels.py
  jupyter_client/client.py
  jupyter_client/multikernelmanager.py
  jupyter_client/tests/test_kernelmanager.py
  jupyter_client/tests/test_multikernelmanager.py
  jupyter_client/threaded.py
  jupyter_client/utils.py
  pyproject.toml
Labels: bug

#775 Automated Changelog Entry for 7.3.0 on main
  CHANGELOG.md
Labels: documentation

#779 Unicode error correction using Error Handler
  jupyter_client/session.py
Labels: bug
