Repository jupyter/jupyter_client, pull requests merged in 2022-02, with the labels that each got.

#742 Use built in run cancellation
  .github/workflows/check-release.yml
  .github/workflows/downstream.yml
  .github/workflows/enforce-label.yml
  .github/workflows/main.yml
Labels: maintenance

#733 Update consoleapp.py
  jupyter_client/consoleapp.py
Labels: enhancement

#743 Prefer sending signals to kernel process group
  jupyter_client/provisioning/local_provisioner.py
Labels: bug
