Repository jupyter/jupyter_client, pull requests merged in 2022-03, with the labels that each got.

#750 Clean up dependency handling
  .github/workflows/check-release.yml
  .github/workflows/downstream.yml
  .github/workflows/main.yml
  .pre-commit-config.yaml
  jupyter_client/channels.py
  jupyter_client/session.py
  jupyter_client/ssh/tunnel.py
  jupyter_client/tests/test_connect.py
  jupyter_client/tests/test_kernelmanager.py
  jupyter_client/tests/test_manager.py
  jupyter_client/tests/test_provisioning.py
  jupyter_client/tests/test_session.py
  jupyter_client/tests/utils.py
  pyproject.toml
  requirements-test.txt
  requirements.txt
  setup.py
Labels: maintenance

#752 Json packer: handle TypeError and fallback to old json_clean
  jupyter_client/session.py
Labels: bug

#757 Add pytest opts and clean up workflows
  .github/workflows/main.yml
  CHANGELOG.md
  docs/provisioning.rst
  docs/wrapperkernels.rst
  jupyter_client/tests/test_session.py
  pyproject.toml
  requirements-doc.txt
Labels: maintenance

#758 Mock is not needed
  requirements-test.txt
Labels: maintenance

#759 Automated Changelog Entry for 7.2.0 on main
  CHANGELOG.md
Labels: documentation

#760 Handle Warnings
  .github/workflows/downstream.yml
  .github/workflows/main.yml
  jupyter_client/client.py
  jupyter_client/kernelspec.py
  jupyter_client/kernelspecapp.py
  jupyter_client/manager.py
  jupyter_client/provisioning/local_provisioner.py
  jupyter_client/ssh/tunnel.py
  jupyter_client/tests/conftest.py
  jupyter_client/tests/test_client.py
  jupyter_client/tests/test_kernelmanager.py
  jupyter_client/tests/test_multikernelmanager.py
  jupyter_client/tests/test_provisioning.py
  jupyter_client/tests/test_session.py
  jupyter_client/tests/test_utils.py
  jupyter_client/tests/utils.py
  jupyter_client/utils.py
  pyproject.toml
  requirements-test.txt
  requirements.txt
Labels: maintenance
