Repository jupyter/jupyter_client, pull requests merged in 2022-06, with the labels that each got.

#801 Add local-provisioner entry point to pyproject.toml Fixes #800
  pyproject.toml
Labels: bug

#802 Automated Changelog Entry for 7.3.3 on main
  CHANGELOG.md
Labels: documentation

#803 Revert latest changes to `ThreadedZMQSocketChannel` because they break Qtconsole
  .github/workflows/downstream.yml
  jupyter_client/threaded.py
Labels: bug

#804 Fix sphinx 5.0 support
  docs/conf.py
Labels: maintenance

#805 Automated Changelog Entry for 7.3.4 on main
  CHANGELOG.md
Labels: documentation
