Repository jupyter/jupyter_client, pull requests merged in 2022-09, with the labels that each got.

#834 Move tests to top level
  .flake8
  .github/workflows/main.yml
  .pre-commit-config.yaml
  pyproject.toml
  tests/__init__.py
  tests/conftest.py
  tests/problemkernel.py
  tests/signalkernel.py
  tests/test_adapter.py
  tests/test_client.py
  tests/test_connect.py
  tests/test_jsonutil.py
  tests/test_kernelapp.py
  tests/test_kernelmanager.py
  tests/test_kernelspec.py
  tests/test_localinterfaces.py
  tests/test_manager.py
  tests/test_multikernelmanager.py
  tests/test_provisioning.py
  tests/test_public_api.py
  tests/test_restarter.py
  tests/test_session.py
  tests/test_ssh.py
  tests/utils.py
Labels: maintenance

#832 Add Jupyter Events and emit events from the Kernel Manager
  jupyter_client/__init__.py
  jupyter_client/event_schemas/kernel_manager/v1.yaml
  jupyter_client/manager.py
  pyproject.toml
  tests/conftest.py
  tests/test_kernelmanager.py
  tests/test_manager.py
Labels: enhancement

#837 Use hatch for version
  RELEASING.md
  pyproject.toml
Labels: maintenance

#840 Switch to pydata sphinx theme
  docs/conf.py
  pyproject.toml
Labels: documentation
