Repository jupyter/jupyter_client, pull requests merged in 2022-01, with the labels that each got.

#731 Test against all kernels in jupyter kernel test and clean up CI
  .github/workflows/check-release.yml
  .github/workflows/downstream.yml
  .github/workflows/main.yml
Labels: maintenance

#732 Further improvements to pending kernels managment
  .github/workflows/downstream.yml
  docs/index.rst
  docs/pending-kernels.rst
  jupyter_client/manager.py
  jupyter_client/multikernelmanager.py
  jupyter_client/tests/test_multikernelmanager.py
Labels: enhancement

#738 Automated Changelog Entry for 7.1.1 on main
  CHANGELOG.md
Labels: documentation

#740 Await `kernel.ready` in `_async_shutdown_kernel`
  jupyter_client/multikernelmanager.py
Labels: bug

#741 Automated Changelog Entry for 7.1.2 on main
  CHANGELOG.md
Labels: documentation
