Repository jupyter/jupyter_client, pull requests merged in 2022-10, with the labels that each got.

#844 Ignore warnings in prereleases test
  .github/workflows/main.yml
Labels: maintenance

#835 Remove nest-asyncio dependency
  .github/workflows/downstream.yml
  .github/workflows/main.yml
  jupyter_client/asynchronous/client.py
  jupyter_client/blocking/client.py
  jupyter_client/channels.py
  jupyter_client/client.py
  jupyter_client/ioloop/manager.py
  jupyter_client/manager.py
  jupyter_client/multikernelmanager.py
  jupyter_client/provisioning/local_provisioner.py
  jupyter_client/session.py
  jupyter_client/threaded.py
  jupyter_client/utils.py
  pyproject.toml
  tests/test_client.py
  tests/test_kernelmanager.py
  tests/test_multikernelmanager.py
  tests/test_restarter.py
  tests/test_session.py
  tests/utils.py
Labels: enhancement

#845 Fix pending kernels again
  jupyter_client/manager.py
  jupyter_client/multikernelmanager.py
  tests/test_kernelmanager.py
  tests/test_multikernelmanager.py
Labels: bug

#848 Backport PR #845: Fix pending kernels again
  .github/workflows/main.yml
  jupyter_client/manager.py
  jupyter_client/multikernelmanager.py
  jupyter_client/tests/test_kernelmanager.py
  jupyter_client/tests/test_multikernelmanager.py
Labels: bug

#851 Revert "Backport PR #845: Fix pending kernels again"
  .github/workflows/main.yml
  jupyter_client/manager.py
  jupyter_client/multikernelmanager.py
  jupyter_client/tests/test_kernelmanager.py
  jupyter_client/tests/test_multikernelmanager.py
Labels: bug

#852 Fix ready promise and session send
  .github/workflows/main.yml
  jupyter_client/manager.py
  jupyter_client/session.py
Labels: bug

#853 Revert "Fix pending kernels again"
  jupyter_client/manager.py
  jupyter_client/multikernelmanager.py
  tests/test_kernelmanager.py
  tests/test_multikernelmanager.py
Labels: bug

#854 Fix handling of initial ready promise
  jupyter_client/manager.py
Labels: bug

#849 Remove usage of jupyter_events
  .github/workflows/main.yml
  jupyter_client/__init__.py
  jupyter_client/event_schemas/kernel_manager/v1.yaml
  jupyter_client/manager.py
  pyproject.toml
  tests/conftest.py
  tests/test_kernelmanager.py
  tests/test_manager.py
Labels: maintenance

#859 Backport PR #858 on branch 7.x (Defer creation of ready future)
  jupyter_client/manager.py
  pyproject.toml
Labels: bug

#860 Fix assertion in `TestSession.test_serialize`
  tests/test_session.py
Labels: maintenance

#861 Workaround for launch bug
  jupyter_client/connect.py
Labels: bug

#862 Backport PR #861 on branch 7.x (Workaround for launch bug)
  jupyter_client/connect.py
Labels: bug

#865 Clean up 7.x workflows
  .github/workflows/check-release.yml
  .github/workflows/downstream.yml
  .github/workflows/main.yml
Labels: maintenance
