Repository jupyter/jupyter_client, pull requests merged in 2022-05, with the labels that each got.

#784 Allow bot PRs to be automatically labeled
  .github/workflows/enforce-label.yml
Labels: maintenance

#785 Check that channels exist before asking if they are alive
  jupyter_client/client.py
Labels: bug

#786 Automated Changelog Entry for 7.3.1 on main
  CHANGELOG.md
Labels: documentation

#781 Use flit build backend
  .flake8
  .github/workflows/main.yml
  MANIFEST.in
  RELEASING.md
  jupyter_client/__init__.py
  pyproject.toml
  readthedocs.yml
  requirements-doc.txt
  requirements-test.txt
  requirements.txt
  setup.py
Labels: maintenance

#789 Use hatch backend
  pyproject.toml
Labels: maintenance

#791 Correct `Any` type annotations.
  jupyter_client/channels.py
  jupyter_client/client.py
  jupyter_client/manager.py
  jupyter_client/multikernelmanager.py
  jupyter_client/session.py
  jupyter_client/threaded.py
  pyproject.toml
Labels: enhancement
