Repository jupyter/jupyter_client, pull requests merged in 2022-12, with the labels that each got.

#893 Make sure loop is marked with nest_asyncio
  jupyter_client/threaded.py
Labels: bug

#896 Fix jupyter_core pinning
  pyproject.toml
Labels: maintenance

#895 Adopt ruff and reduce pre-commit usage
  .github/dependabot.yml
  .github/workflows/main.yml
  .pre-commit-config.yaml
  docs/conf.py
  jupyter_client/_version.py
  jupyter_client/adapter.py
  jupyter_client/asynchronous/client.py
  jupyter_client/blocking/client.py
  jupyter_client/channels.py
  jupyter_client/client.py
  jupyter_client/clientabc.py
  jupyter_client/connect.py
  jupyter_client/consoleapp.py
  jupyter_client/ioloop/manager.py
  jupyter_client/jsonutil.py
  jupyter_client/kernelapp.py
  jupyter_client/kernelspec.py
  jupyter_client/kernelspecapp.py
  jupyter_client/launcher.py
  jupyter_client/localinterfaces.py
  jupyter_client/manager.py
  jupyter_client/multikernelmanager.py
  jupyter_client/provisioning/factory.py
  jupyter_client/provisioning/local_provisioner.py
  jupyter_client/provisioning/provisioner_base.py
  jupyter_client/restarter.py
  jupyter_client/runapp.py
  jupyter_client/session.py
  jupyter_client/ssh/tunnel.py
  jupyter_client/threaded.py
  jupyter_client/utils.py
  jupyter_client/win_interrupt.py
  pyproject.toml
  tests/conftest.py
  tests/signalkernel.py
  tests/test_adapter.py
  tests/test_client.py
  tests/test_connect.py
  tests/test_consoleapp.py
  tests/test_jsonutil.py
  tests/test_kernelapp.py
  tests/test_kernelmanager.py
  tests/test_kernelspec.py
  tests/test_kernelspecapp.py
  tests/test_multikernelmanager.py
  tests/test_provisioning.py
  tests/test_public_api.py
  tests/test_restarter.py
  tests/test_session.py
  tests/test_ssh.py
  tests/utils.py
Labels: maintenance

#898 Allow interrupt during restart of pending kernels
  jupyter_client/consoleapp.py
  jupyter_client/kernelspecapp.py
  jupyter_client/manager.py
  tests/test_multikernelmanager.py
Labels: bug

#899 Allow releasing from repo
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  .pre-commit-config.yaml
  RELEASING.md
  jupyter_client/client.py
  jupyter_client/clientabc.py
  jupyter_client/threaded.py
  pyproject.toml
Labels: maintenance

#903 Add more ci checks
  .github/workflows/main.yml
  .pre-commit-config.yaml
  docs/conf.py
  jupyter_client/_version.py
  jupyter_client/adapter.py
  jupyter_client/asynchronous/client.py
  jupyter_client/blocking/client.py
  jupyter_client/channels.py
  jupyter_client/channelsabc.py
  jupyter_client/clientabc.py
  jupyter_client/consoleapp.py
  jupyter_client/ioloop/manager.py
  jupyter_client/ioloop/restarter.py
  jupyter_client/kernelapp.py
  jupyter_client/kernelspec.py
  jupyter_client/kernelspecapp.py
  jupyter_client/manager.py
  jupyter_client/managerabc.py
  jupyter_client/provisioning/factory.py
  jupyter_client/provisioning/local_provisioner.py
  jupyter_client/runapp.py
  jupyter_client/session.py
  jupyter_client/ssh/forward.py
  jupyter_client/threaded.py
  pyproject.toml
Labels: documentation, maintenance

#905 MAINT: [_async_]start_kernel should only take kwarg only.
  jupyter_client/multikernelmanager.py
  tests/utils.py
Labels: maintenance

#906 MAINT: Proper typing and cast
  jupyter_client/kernelspecapp.py
  jupyter_client/manager.py
Labels: maintenance
