Repository jupyter/jupyter_client, pull requests merged in 2022-08, with the labels that each got.

#822 Use tornado 6.2's PeriodicCallback in restarter
  .github/workflows/downstream.yml
  jupyter_client/ioloop/restarter.py
  pyproject.toml
Labels: bug

#825 Automated Changelog Entry for 7.3.5 on main
  CHANGELOG.md
Labels: documentation

#826 Use pytest_asyncio fixture
  jupyter_client/tests/test_kernelmanager.py
Labels: bug

#827 Fix nbconvert downstream test
  .github/workflows/downstream.yml
Labels: maintenance
