Repository jupyter/jupyter_client, pull requests merged in 2023-01, with the labels that each got.

#912 MAINT: consistently use relative imports.
  jupyter_client/adapter.py
  jupyter_client/asynchronous/client.py
  jupyter_client/blocking/client.py
  jupyter_client/channels.py
  jupyter_client/client.py
  jupyter_client/connect.py
  jupyter_client/ioloop/manager.py
  jupyter_client/ioloop/restarter.py
  jupyter_client/kernelspec.py
  jupyter_client/manager.py
  jupyter_client/session.py
  jupyter_client/ssh/__init__.py
  jupyter_client/threaded.py
  tests/test_client.py
Labels: maintenance

#916 [7.x] Remove deprecated zmq imports
  jupyter_client/ioloop/restarter.py
  jupyter_client/session.py
  jupyter_client/threaded.py
  pyproject.toml
Labels: maintenance

#914 Make Qtconsole work with PyZMQ 25
  jupyter_client/threaded.py
Labels: bug

#915 Remove deprecated zmq imports
  .github/workflows/downstream.yml
  jupyter_client/ioloop/restarter.py
  jupyter_client/session.py
  tests/test_session.py
Labels: maintenance

#917 Fix downstream tests
  .github/workflows/downstream.yml
Labels: maintenance

#911 Sync lint deps
  .pre-commit-config.yaml
  pyproject.toml
Labels: maintenance

#908 Add full api docs
  .github/workflows/main.yml
  docs/api/client.rst
  docs/api/index.rst
  docs/api/jupyter_client.asynchronous.rst
  docs/api/jupyter_client.blocking.rst
  docs/api/jupyter_client.ioloop.rst
  docs/api/jupyter_client.provisioning.rst
  docs/api/jupyter_client.rst
  docs/api/jupyter_client.ssh.rst
  docs/api/kernelspec.rst
  docs/api/manager.rst
  docs/api/modules.rst
  docs/api/provisioners.rst
  docs/conf.py
  docs/index.rst
  jupyter_client/multikernelmanager.py
  jupyter_client/provisioning/factory.py
  pyproject.toml
Labels: documentation

#918 Reflect current protocol version in documentation
  docs/messaging.rst
Labels: documentation

#919 MAINT: Don't format log in log call.
  jupyter_client/connect.py
  jupyter_client/consoleapp.py
  jupyter_client/kernelapp.py
  jupyter_client/kernelspec.py
  jupyter_client/kernelspecapp.py
  jupyter_client/multikernelmanager.py
  jupyter_client/runapp.py
Labels: maintenance

#921 Fix json_output in kernelspec app
  jupyter_client/kernelspecapp.py
Labels: bug

#923 Prefer print in kernelspecapp
  jupyter_client/kernelspecapp.py
  pyproject.toml
Labels: maintenance

#925 Add papermill downstream check and fix kernel client replies
  .github/workflows/downstream.yml
  jupyter_client/asynchronous/client.py
  tests/test_client.py
  tests/test_kernelmanager.py
  tests/test_multikernelmanager.py
Labels: bug

#924 Adopt more ruff rules
  .pre-commit-config.yaml
  jupyter_client/channels.py
  jupyter_client/client.py
  jupyter_client/connect.py
  jupyter_client/ioloop/manager.py
  jupyter_client/jsonutil.py
  jupyter_client/kernelspec.py
  jupyter_client/launcher.py
  jupyter_client/localinterfaces.py
  jupyter_client/manager.py
  jupyter_client/multikernelmanager.py
  jupyter_client/provisioning/factory.py
  jupyter_client/provisioning/local_provisioner.py
  jupyter_client/restarter.py
  jupyter_client/runapp.py
  jupyter_client/session.py
  jupyter_client/ssh/tunnel.py
  jupyter_client/utils.py
  pyproject.toml
  tests/test_jsonutil.py
  tests/test_provisioning.py
Labels: maintenance
