Repository jupyter/jupyter_client, pull requests merged in 2023-10, with the labels that each got.

#974 Update typings for traitlets 5.10.1
  docs/conf.py
  jupyter_client/client.py
  jupyter_client/connect.py
  jupyter_client/consoleapp.py
  jupyter_client/ioloop/manager.py
  jupyter_client/kernelspec.py
  jupyter_client/kernelspecapp.py
  jupyter_client/manager.py
  jupyter_client/multikernelmanager.py
  jupyter_client/runapp.py
  jupyter_client/session.py
  jupyter_client/threaded.py
  pyproject.toml
  tests/problemkernel.py
  tests/signalkernel.py
  tests/test_kernelspec.py
Labels: maintenance

#977 Update typing for traitlets 5.11
  jupyter_client/asynchronous/client.py
  jupyter_client/blocking/client.py
  jupyter_client/client.py
  jupyter_client/consoleapp.py
  jupyter_client/kernelspec.py
  jupyter_client/kernelspecapp.py
  jupyter_client/manager.py
  jupyter_client/provisioning/local_provisioner.py
  jupyter_client/threaded.py
  pyproject.toml
  tests/test_client.py
Labels: maintenance

#983 Update typings for mypy 1.6
  docs/conf.py
  jupyter_client/localinterfaces.py
  jupyter_client/ssh/tunnel.py
  pyproject.toml
Labels: maintenance

#987 Allow to update kernels env in between restart.
  jupyter_client/manager.py
  jupyter_client/multikernelmanager.py
Labels: enhancement

#984 Enable strict typing
  docs/conf.py
  jupyter_client/asynchronous/client.py
  jupyter_client/blocking/client.py
  jupyter_client/channels.py
  jupyter_client/channelsabc.py
  jupyter_client/client.py
  jupyter_client/clientabc.py
  jupyter_client/connect.py
  jupyter_client/consoleapp.py
  jupyter_client/ioloop/manager.py
  jupyter_client/ioloop/restarter.py
  jupyter_client/jsonutil.py
  jupyter_client/kernelapp.py
  jupyter_client/kernelspec.py
  jupyter_client/kernelspecapp.py
  jupyter_client/localinterfaces.py
  jupyter_client/manager.py
  jupyter_client/managerabc.py
  jupyter_client/multikernelmanager.py
  jupyter_client/provisioning/factory.py
  jupyter_client/restarter.py
  jupyter_client/runapp.py
  jupyter_client/session.py
  jupyter_client/ssh/forward.py
  jupyter_client/ssh/tunnel.py
  jupyter_client/threaded.py
  jupyter_client/utils.py
  jupyter_client/win_interrupt.py
  pyproject.toml
  tests/test_kernelspecapp.py
  tests/test_localinterfaces.py
Labels: maintenance

#991 Fix possibly not defined tracker
  jupyter_client/session.py
Labels: bug

#992 Use ruff format
  .pre-commit-config.yaml
  docs/conf.py
  jupyter_client/_version.py
  jupyter_client/channels.py
  jupyter_client/consoleapp.py
  jupyter_client/jsonutil.py
  jupyter_client/kernelspec.py
  jupyter_client/kernelspecapp.py
  jupyter_client/manager.py
  jupyter_client/multikernelmanager.py
  jupyter_client/provisioning/factory.py
  jupyter_client/provisioning/local_provisioner.py
  jupyter_client/provisioning/provisioner_base.py
  jupyter_client/session.py
  jupyter_client/ssh/tunnel.py
  jupyter_client/win_interrupt.py
  pyproject.toml
  tests/conftest.py
  tests/test_client.py
  tests/test_jsonutil.py
  tests/test_kernelspecapp.py
  tests/test_localinterfaces.py
  tests/test_multikernelmanager.py
  tests/test_provisioning.py
  tests/test_restarter.py
  tests/test_session.py
Labels: maintenance
