Repository jupyter/jupyter_client, pull requests merged in 2023-02, with the labels that each got.

#929 Improving jsonutil tests
  tests/test_jsonutil.py
Labels: maintenance

#931 Don't emit a trailng newline in base64-encoded data like 'image/png'
  jupyter_client/jsonutil.py
  tests/test_jsonutil.py
Labels: bug

#934 Add license
  COPYING.md
  LICENSE
  README.md
  pyproject.toml
  tests/test_localinterfaces.py
Labels: maintenance

#933 fix kernelspec print output
  jupyter_client/kernelspecapp.py
Labels: bug

#932 Adds spec for the copyToGlobals request
  docs/messaging.rst
Labels: documentation
