Repository jupyter/jupyter_client, pull requests merged in 2024-09, with the labels that each got.

#1027 Avoid a DeprecationWarning on Python 3.13+
  jupyter_client/jsonutil.py
Labels: bug

#1037 fix invocation of pip for nbconvert downstream
  .github/workflows/downstream.yml
Labels: maintenance

#1038 Fix docs check
  .github/workflows/main.yml
Labels: maintenance

#1032 use simpler isoparse from dateutil to parse ISO-8601 timestamps
  jupyter_client/jsonutil.py
Labels: bug

#1033 Support psutil for finding network addresses
  jupyter_client/localinterfaces.py
Labels: enhancement

#1036 test on python 3.13-dev
  .github/workflows/main.yml
  pyproject.toml
Labels: maintenance

#1040 don't include link-local addresses (169.254) in public_ips
  jupyter_client/localinterfaces.py
Labels: bug

#994 jupyter-run: avoid traceback for NoSuchKernel
  jupyter_client/consoleapp.py
  jupyter_client/kernelspec.py
  jupyter_client/runapp.py
  tests/test_runapp.py
Labels: bug
